### Create product
POST http://localhost:8080/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1VTRVIiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTI0OTE4NDYsImV4cCI6MTc1MjQ5NTQ0Nn0.3pwMwm5czMRMq434rP7XKBxMOxB8d-p-Wz4yyPAwR2Q

{
  "name": "Cooking gas",
  "description": "A large cooking gas",
  "price": 3000,
  "stock": 30
}

### get product ID
GET http://localhost:8080/api/product/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1VTRVIiXSwic3ViIjoiZmVtaSIsImlhdCI6MTc1MjQ5MDQ0MCwiZXhwIjoxNzUyNDk0MDQwfQ.gcrNWRHf-fmM7CQILn9FRBE1JYM5JkyrnX6_xETxCAg

{
"name": "Television",
"description": "16 inches television",
"price": 5004.22,
"stock": 134
}


### get all product
GET http://localhost:8080/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1VTRVIiXSwic3ViIjoiZmVtaSIsImlhdCI6MTc1MjQ5MDQ0MCwiZXhwIjoxNzUyNDk0MDQwfQ.gcrNWRHf-fmM7CQILn9FRBE1JYM5JkyrnX6_xETxCAg
